// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2liGU51tJCRC7UC-hWieB4Uk-JBrVT-c',
    appId: '1:1036525008938:web:669b50ee0aef69dda76b53',
    messagingSenderId: '1036525008938',
    projectId: 'mironegocios-app',
    authDomain: 'mironegocios-app.firebaseapp.com',
    storageBucket: 'mironegocios-app.firebasestorage.app',
    measurementId: 'G-5P6T3G5FZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNK-cNpu-eXabj0qB_Vqm488fHQbcvB54',
    appId: '1:448369198333:android:e260e592f2d0311f41ea94',
    messagingSenderId: '448369198333',
    projectId: 'liviase-af055',
    storageBucket: 'liviase-af055.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2liGU51tJCRC7UC-hWieB4Uk-JBrVT-c',
    appId: '1:1036525008938:web:251ccef4ebfea03da76b53',
    messagingSenderId: '1036525008938',
    projectId: 'mironegocios-app',
    authDomain: 'mironegocios-app.firebaseapp.com',
    storageBucket: 'mironegocios-app.firebasestorage.app',
    measurementId: 'G-GFVZJFJ70B',
  );
}
